-- Auto-generated from schema-map-postgres.psd1 (map@mtime:2025-10-24T09:46:38Z)
-- engine: postgres
-- table:  crypto_keys
CREATE TABLE IF NOT EXISTS crypto_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  basename VARCHAR(100) NOT NULL,
  version INTEGER NOT NULL,
  filename VARCHAR(255) NULL,
  file_path VARCHAR(1024) NULL,
  fingerprint CHAR(64) NULL,
  key_meta JSONB NULL,
  key_type TEXT NULL,
  algorithm VARCHAR(64) NULL,
  length_bits SMALLINT NULL,
  origin TEXT NULL,
  "usage" TEXT[] NULL,
  scope VARCHAR(100) NULL,
  status TEXT NOT NULL DEFAULT 'active',
  is_backup_encrypted BOOLEAN NOT NULL DEFAULT FALSE,
  backup_blob BYTEA NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  activated_at TIMESTAMPTZ(6) NULL,
  retired_at TIMESTAMPTZ(6) NULL,
  replaced_by BIGINT NULL,
  notes TEXT NULL,
  CONSTRAINT uq_keys_basename_version UNIQUE (basename, version),
  CONSTRAINT chk_keys_type    CHECK (key_type IS NULL OR key_type IN ('dek','kek','hmac','pepper')),
  CONSTRAINT chk_keys_origin  CHECK (origin IS NULL OR origin IN ('local','kms','imported')),
  CONSTRAINT chk_keys_status  CHECK (status IN ('active','retired','compromised','archived')),
  CONSTRAINT chk_keys_usage   CHECK (usage IS NULL OR usage <@ ARRAY['encrypt','decrypt','sign','verify','wrap','unwrap'])
);
